package com.ashwetaw.springbootgenericcrud.entities;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.Data;

/**
 * @author koheincs
 * @created at 26/04/2024
 **/
@Data
@DynamoDBTable(tableName = "employee")
public class Employee {
    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String id;
    private String name;
    private String phone;
    private String email;
    private String position;
    private String bio;
}
