package com.ashwetaw.springbootgenericcrud.entities;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.Data;

/**
 * @author koheincs
 * @created at 02/05/2024
 **/
@Data
@DynamoDBTable(tableName = "user")
public class User {
    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String id;
    private String username;
    private String password;
}
